// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"ennoaragon/internal/static/data"
	"ennoaragon/internal/templates/partials"
)

// <img src="/assets/Team_victory.webp" class="w-full h-[40vh] object-cover rounded-lg" alt="Team victory">
func About(carousel []data.ImageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col items-center h-fit\"><div class=\"mt-10\"><video class=\"w-full h-[40vh] object-cover rounded-lg\" alt=\"Team victory\" controls autoplay muted loop><source src=\"/assets/jumbo_cam_heart.mp4\" type=\"video/mp4\" ng-if=\"option==&#39;video&#39;\"></video></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = partials.Slider(carousel).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-left  max-w-[60%]\"><p class=\"text-xl\">I was an professional eSports player and turned my hobby of coding into my career. I enjoy full stack development and have passion for creating a great UX experience for users. I am a quick learner and always looking to improve my skills.</p><p class=\"text-xl\">I look foward to working on cutting edge projects, emphasis of bringing useful and innovative solutions users.</p></div><div class=\"text-left  max-w-[60%]\"><p class=\"text-xl\">I was an professional eSports player and turned my hobby of coding into my career. I enjoy full stack development and have passion for creating a great UX experience for users. I am a quick learner and always looking to improve my skills.</p><p class=\"text-xl\">I look foward to working on cutting edge projects, emphasis of bringing useful and innovative solutions users.</p></div><div class=\"text-left  max-w-[60%]\"><p class=\"text-xl\">I was an professional eSports player and turned my hobby of coding into my career. I enjoy full stack development and have passion for creating a great UX experience for users. I am a quick learner and always looking to improve my skills.</p><p class=\"text-xl\">I look foward to working on cutting edge projects, emphasis of bringing useful and innovative solutions users.</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
