// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col items-center justify-center w-full h-fit mt-24\"><div class=\"text-left w-home-max max-w-home-max text-wrap mx-auto \"><p class=\"text-7xl\">Enno Aragon</p><p class=\"text-base mt-6\">Hey, I’m Enno Aragon an ex pro-gamer turned programmer.</p><p class=\"text-base mt-6\">My journey began in 2016 when I embarked  on building a website for my father’s business, finding the  complexities of backend and frontend development both challenging  and captivating. Shortly after, my eSports career took off, you can  read more about it <a class=\"text-secondary\" href=\"/about\">here </a>.  Over the years, I've developed software during my content creation  and gaming days, worked at a  <a class=\"text-secondary\" href=\"https://signup.buildbox.com/\">startup</a>,  and tackled ambitious projects at  <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://idropstudios.com\" class=\"text-secondary\">iDropStudios</a>.</p><p class=\"text-base mt-6\">I'm focused on honing my engineering  skills by developing desktop and web applications that enhance  UX, including CLI tools, and Discord bots for D&D for friends.  I'm also exploring video game development. Each project refines  my skills and broadens my perspective. Learn more about my work <a class=\"text-secondary\" href=\"/projects\">here</a>.</p><p class=\"text-base mt-6\">When I'm not working on a project, you'll  find me outdoors hiking, capturing landscapes through  photography, staying active, or ticking off destinations from  my travel bucket list. Check out some of my favorite shots <a class=\"text-secondary\" href=\"/about\">here</a>.</p><ul class=\"text-base mt-4\"><li class=\"text-base\">👨\u200d💻 Software Engineer</li><li class=\"text-base\">🎮 Ex Pro-Gamer</li><li class=\"text-base\">📸 Photographer</li><li class=\"text-base\">🏞️ Traveler</li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
