export interface iProject{
    id: number,
    company?: string,
    title: string,
    description: string,
    tasks: string[],
    image_src: string,
    video_src: string,
    local_src?: string,
    tech_chips: string[],
    date: string,
    external_url: string,
    github_url: string,
    more_links?: string[],
    hide?: boolean,
}

export const projects:iProject[] = [
//    {
//        id: 0,
//        title: "Team fire cracker",
//        description: "Join an adventurous cat and its AI companion on a secret mission from Earth in this 2.5D platformer. The game aims to deliver an immersive experience, utilizing GPT agents to craft engaging and interactive conversations between the characters, enhancing the overall gameplay and narrative depth.",
//        tasks: [],
//        image_src: "https://tenor.com/view/kitty-cat-sandwich-cats-sandwich-gif-26112528",
//        tech_chips: ["Unreal Engine 5", "c++", "Chat GPT", "python"],
//        date: "2021-09-01",
//        external_url: "",
//        github_url: "",
//        local_src: "src/assets/",
//        video_src: "",
//        hide: true,
//    },
    {
        id: 0,
        title: "Joy Tap",
        description: "The product is a stress-relief desktop application with a video game window overlay. With a tap of a key, the application will play a video overlay during gameplay intermissions; press again to minimize. The lightweight Application is built using",
        tasks: [],
        image_src: "https://tenor.com/view/kitty-cat-sandwich-cats-sandwich-gif-26112528",
        tech_chips: ["Svelte", "Tauri", "Rust", "Tailwindcss", "GCP", "GO"],
        date: "2021-09-01",
        external_url: "",
        github_url: "",
        local_src: "src/assets/joytap.webp",
        video_src: "",
        hide: false,
    },
    {
        id: 1,
        title: "Canvas Swap",
        description: "A collaborative and timed art challenge where participants paint on a shared canvas for set intervals, then swap with others to continue adding to their work, with gameplay that allows to aid or hinder your drawing partner(s). The experience gives a spontaneous, creative collaborations, with the finished piece often reflecting artists' unique styles and touches before returning to the original owner completion. ",
        tasks: [],
        image_src: "https://tenor.com/view/kitty-cat-sandwich-cats-sandwich-gif-26112528",
        tech_chips: ["React", "zustand", "GO", "Tailwindcss","AWS"],
        date: "2021-09-01",
        external_url: "",
        github_url: "",
        local_src: "src/assets/swapcanvas.webp",
        video_src: "",
        hide: false,
    },
    {
        id: 2,
        title: "Naoux",
        description: "Led the team by designing and developing a clothing store using Agile/Scrum principles with a team of three members. Developed the backend using third-party services to fulfill physical item shipments. Created an SMTP service for order placements",
        tasks: [],
        image_src: "https://tenor.com/view/kitty-cat-sandwich-cats-sandwich-gif-26112528",
        tech_chips: ["React","Redux", "Firebase", "Express", "Material UI", "Stripe" ],
        date: "2021-09-01",
        external_url: "https://www.naoux.co/",
        github_url: "",
        local_src: "src/assets/naoux_outdoors.webp",
        video_src: "",
        hide: false,
    },
    {
        id: 3,
        title: "The Tavern",
        description: "Developed interactive tools catering to diverse role-playing needs, enabling users to save documents, information, and images to NoSQL datebases. Implemented real-time item saving and display alongside an interactive map system for coordinating information.",
        tasks: [],
        image_src: "https://tenor.com/view/kitty-cat-sandwich-cats-sandwich-gif-26112528",
        tech_chips: ["React","Redux", "Firebase", "Express", "Material UI", "Stripe" ],
        date: "2021-09-01",
        external_url: "https://www.thetavern.io/",
        github_url: "",
        local_src: "src/assets/thetavern.webp",
        video_src: "",
        hide: false,
    }
]
